### ISSUE TITLE
Authentication Issue (unexpected status code: 401) on Replica despite app_sudo=true

### ISSUE THREAD

**Issue by RadTunesly** [lovelaze/nebula-sync#155]
I have two Pihole containers running on two Synology NAS. I updated to v6 a couple of months ago and have just realised that Orbital Sync has been archived which led me to Nebula-Sync. I just updated to the latest docker images on the pihole containers (Docker Tag 2025.05.1 Core v6.1 FTL v6.2 Web interface v6.2.1) and added created a Nebula-Sync container to keep them in sync.

On first attempt to stand the container up received `WRN Failed to invalidate session for target: <pihole url>` followed by `FTL Sync failed error="run gravity: <pihole url>/api/action/gravity: unexpected status code: 401"`   for both piholes, then checked the README properly and noticed that this issue is covered. For the primary I resolved the issue via the web interface: Settings > All Settings > Webserver and API > webserver.api.app_sudo [Enabled].

The Replica pihole, for some reason, doesn't have the "All Settings" option in the under "Settings", so I bashed into the container and changed `app_sudo = true` in pihole.toml directly.

Now when I start the Nebula Sync container, the sync is working but it fails when invalidating the session and stops the container. Log:
```
2025-06-01T13:22:04+10:00 INF Starting nebula-sync v0.11.0
2025-06-01T13:22:04+10:00 INF Running sync mode=full replicas=1
2025-06-01T13:22:04+10:00 INF Authenticating clients...
2025-06-01T13:22:05+10:00 INF Syncing teleporters...
2025-06-01T13:22:05+10:00 INF Syncing configs...
2025-06-01T13:22:05+10:00 INF Running gravity...
2025-06-01T13:23:45+10:00 INF Invalidating sessions...
2025-06-01T13:24:25+10:00 WRN Failed to invalidate session for target: https://<replica pihole URL>
2025-06-01T13:24:25+10:00 FTL Sync failed error="run gravity: https://<replica pihole URL>/api/action/gravity: unexpected status code: 401"
```

I'm newish to piholes, containers and Linux, so I'd wager I'm missing something obvious. I'm wondering if you might be able to point me in the right direction.

Many thanks

**Comment by derritter88** [comment]
Same here:
Pi-hole 6.0.6 works
Pihole 6.1.2 works not

**Comment by PromoFaux** [comment]
Can you try the `pihole:development` docker tag? 

There is a recognised issue with 6.2 / 6.2.1. development contains 6.2.2 - I've not yet tagged it as master as want to confirm the crashes are fixed

**Comment by RadTunesly** [comment]
Thank you for your replies.

I have updated both pihole images, now showing **Docker Tag** 2025.06.1 **Core** v6.1.2 **FTL** v6.2.2 **Web interface** v6.2.1

I'm no longer getting `unexpected status code: 401`

Unfortunately I've got a new error (which is always progress). I suspect this is not related to Nebula-Sync but will ask here anyway just in case anyone has some insight.

Gravity Sync Log:
```
2025-06-07T13:20:25+10:00 INF Starting nebula-sync v0.11.0
2025-06-07T13:20:25+10:00 INF Running sync mode=full replicas=1
2025-06-07T13:20:25+10:00 INF Authenticating clients...
2025-06-07T13:20:26+10:00 INF Syncing teleporters...
2025-06-07T13:20:26+10:00 INF Syncing configs...
2025-06-07T13:20:26+10:00 INF Running gravity...
2025-06-07T13:20:46+10:00 INF Invalidating sessions...
2025-06-07T13:21:46+10:00 WRN Failed to invalidate session for target: https://<replica pihole URL>/
2025-06-07T13:21:46+10:00 FTL Sync failed error="run gravity: https://<primary pihole URL>/api/action/gravity: Post \"https://<primary pihole URL>/api/action/gravity\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

I investigated the replica pihole logs and also found this (though not sure it is related):
```
2025-06-07 13:18:31.544 AEST [53M] ERROR: SQLite3: table aliasclient already exists in "CREATE TABLE aliasclient (id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL, comment TEXT);" (1)
2025-06-07 13:18:31.544 AEST [53M] ERROR: ERROR: SQL query "CREATE TABLE aliasclient (id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL, comment TEXT);" failed: SQL logic error (SQLITE_ERROR)
2025-06-07 13:18:31.544 AEST [53M] ERROR: create_aliasclients_table() failed!
2025-06-07 13:18:31.544 AEST [53M] ERROR: Aliasclients table not initialized, database not available
2025-06-07 13:18:31.547 AEST [53M] ERROR: init_memory_database(): Failed to attach disk database
```

The sync seems to work but the Nebula-Sync container stops when it hits the error above.

Any ideas?

**Comment by lancer199135** [comment]
@RadTunesly same issue as your first post with the exception of I'm getting FTL Sync authenticate error, but I'm already on the updated docker pi-hole Docker Tag 2025.06.2 Core v6.1.2 FTL v6.2.3 Web interface v6.2, but still getting same errors. So just an update cleared those errors for you? I have the webserver.api.app_sudo "enabled". I have my replica in Docker via Portainer with primary on a standalone pi zero w. Were you able to get this working at all?

`2025-06-21T16:23:15-04:00 INF Starting nebula-sync v0.11.0

2025-06-21T16:23:15-04:00 INF Running sync mode=full replicas=1

2025-06-21T16:23:15-04:00 INF Authenticating clients...

2025-06-21T16:23:29-04:00 INF Invalidating sessions...

2025-06-21T16:23:31-04:00 WRN Failed to invalidate session for target: http://192.168.1.10

2025-06-21T16:23:31-04:00 FTL Sync failed error="authenticate: http://192.168.1.10/api/auth: Post \"http://192.168.1.10/api/auth\": dial tcp 192.168.1.10:80: connect: no route to host"`

**Comment by lancer199135** [comment]
@RadTunesly my issue may be network access as I made a Macvlan for the my replicas pi-hole as that is within a portafilter container. My main is on its own device. I was having issues with accessing the container version and understanding IP it assigned for use with of sense so I researched Macvlan. Doing don't reading messages it seem like that's the case. I'll start looking how to reverse things and get it working. Thanks for pointing me in a direction.

**Comment by lancer199135** [comment]
@RadTunesly sorry was suppose to say "Portainer" and autocorrect got me. I went into SSH on my raspberry pi and did the following commands from your link as I already created before the macvlan within Portainer's network environment and all is working now.

```sudo ip link set eth0 promisc on```
```sudo ip link add macvlan-shim link eth0 type macvlan mode bridge```
```sudo ip addr add 192.168.1.11/28 dev macvlan-shim```
As I wasn't sure how to add ```aux-address``` in portainer I'm hoping for the best that the .11 doesn't cause conflict as I assigned .10 to my backup pi-hole to access web admin.

Thanks for your help. Wish I could help you, but I'm just a construction contractor, so this is all unknown to me.

**Comment by RadTunesly** [comment]
@lancer199135 lol at portafilter. That should have been obvious. I actually googled it and came up with a lot of espresso machine related results. Figured it was some obscure container implementation. Networking while braindead from work...

Nice work on getting it going with the macvlan-shim. I would recommend getting the aux address sorted out to avoid any weird failures/conflict issues in future. I believe this can be achieved in Portainer when you're setting up the network under "IPV4 Network configuration" there is an option for "+ Add Excluded IP", where you can add your "192.168.1.11". You would need to delete your existing macvlan network and recreate it but if you already have all the parameters already it should only take a few minutes. Just take a screenshot of the network macvlan details before you delete it.

And thanks heaps, changing run_gravity to false did stop the container failing. I now need to find out why running gravity was causing the errors. It was pretty obvious after you shined the torch on it for me though. Much appreciated!

**Comment by hspindel** [comment]
I am just starting out with Nebula Sync.  I am getting the same error as reported above: Failed to authenticate unexpected status code 401.

Pihole 6.1.4 FTL 6.2.3 Web Interface 6.2.1.  pihole -up reports I have the latest.

I am not running pihole in a container - it is on a Debian VM. I changed app_sudo = true in pihole.toml .  Rebooted the Debian VM but no success.

![Image](https://github.com/user-attachments/assets/67a1ee77-6c4b-4b75-96d9-3b73317ee0c4)

Any updates on this issue?
